flat_first.Rmd:
  path: dev/flat_first.Rmd
  state: active
  R:
  - R/my_median.R
  - R/my_other_median.R
  tests:
  - tests/testthat/test-my_median.R
  - tests/testthat/test-my_other_median.R
  vignettes: vignettes/get-started.Rmd
  inflate:
    flat_file: dev/flat_first.Rmd
    vignette_name: Get started
    open_vignette: true
    check: true
    document: true
    overwrite: ask
flat_plot_urgara.Rmd:
  path: dev/flat_plot_urgara.Rmd
  state: active
  R:
  - R/fct_plot_charge.R
  - R/fct_tab_charge.R
  - R/plot_add_logo.R
  - R/plot_diag_charge.R
  - R/na-na.R
  tests:
  - tests/testthat/test-plot_diag_charge.R
  - tests/testthat/test-plot_add_logo.R
  - tests/testthat/test-fct_tab_charge.R
  - tests/testthat/test-fct_plot_charge.R
  vignettes: vignettes/test.Rmd
  inflate:
    flat_file: dev/flat_plot_urgara.Rmd
    vignette_name: test
    open_vignette: false
    check: true
    document: true
    overwrite: ask
